<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Log in</name>
   <tag></tag>
   <elementGuidId>a29835ca-8bc1-4a7a-9f74-6ca14780bcc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ant-btn.css-w8mnev.ant-btn-primary.login-form-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>da003aaf-f200-452f-8e19-a5be92ed51e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>7b7b4bbd-e12a-4406-b6bb-0e3ba5a96a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn css-w8mnev ant-btn-primary login-form-button</value>
      <webElementGuid>b5ecb2e8-f78f-40c7-9c6c-5924d6f8b1ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log in</value>
      <webElementGuid>56437b1e-1da6-4314-b47c-8ccc669b9a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;normal_login&quot;)/div[@class=&quot;ant-form-item css-w8mnev&quot;]/div[@class=&quot;ant-row ant-form-item-row css-w8mnev&quot;]/div[@class=&quot;ant-col ant-form-item-control css-w8mnev&quot;]/div[@class=&quot;ant-form-item-control-input&quot;]/div[@class=&quot;ant-form-item-control-input-content&quot;]/button[@class=&quot;ant-btn css-w8mnev ant-btn-primary login-form-button&quot;]</value>
      <webElementGuid>219d227b-904a-43c4-b957-90698757eaa3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>96693ca6-91d7-4146-9e82-f0d706688db8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='normal_login']/div[3]/div/div/div/div/button</value>
      <webElementGuid>7d7719cb-432c-4737-b24b-4bff4bf3e53b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login Failed'])[1]/preceding::button[2]</value>
      <webElementGuid>f384be58-d875-422d-b356-9510a035cf08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>19b080fa-0440-4caf-ab57-0f14162b8f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Log in' or . = 'Log in')]</value>
      <webElementGuid>855fc9aa-2e00-420b-9256-364fb20d4440</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
