<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_LoginPlease fill in your unique admin l_a3a9c8</name>
   <tag></tag>
   <elementGuidId>af562b37-5f2d-4df0-aab3-96c92cd4bb98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ant-card-body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4989b2b3-d283-4725-8a06-08d4cad4676e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-card-body</value>
      <webElementGuid>d57740c9-da2a-40d1-8248-3ef7221516e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LoginPlease fill in your unique admin login details belowEmail AddressPasswordLog in</value>
      <webElementGuid>b4fa1c4b-6d12-4e30-939b-74b5289986ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;background-container&quot;]/div[@class=&quot;login-container&quot;]/div[@class=&quot;ant-card ant-card-bordered login-card css-w8mnev&quot;]/div[@class=&quot;ant-card-body&quot;]</value>
      <webElementGuid>6f1dfaf3-ad2a-4462-ac48-f648908d4035</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div</value>
      <webElementGuid>318e48f0-8ea5-434a-8c3a-29a4be42d94a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login Failed'])[1]/preceding::div[19]</value>
      <webElementGuid>264eb77a-72de-48b8-8fb8-86ac50179a7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div</value>
      <webElementGuid>9dd4bbff-45a4-42c6-afa7-c3f8e014b62c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'LoginPlease fill in your unique admin login details belowEmail AddressPasswordLog in' or . = 'LoginPlease fill in your unique admin login details belowEmail AddressPasswordLog in')]</value>
      <webElementGuid>b1fb1d15-273e-4e8e-86a2-c6b077251475</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
