<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Log in_normal_login_username</name>
   <tag></tag>
   <elementGuidId>c44ba68c-1ccd-41ce-b6f0-1bc9e9016edb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#normal_login_username</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='normal_login_username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b09c57d-e984-41c5-ad2f-f25b25896fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email Address</value>
      <webElementGuid>b77c9d19-d976-4bf5-bffa-9b0d6ca4a174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>normal_login_username</value>
      <webElementGuid>00f2d87f-5d68-4840-8d21-c48c21a4dbeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>94770617-388b-4d53-aa7d-458276ad58aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input css-w8mnev</value>
      <webElementGuid>b40f9d99-e1a8-433a-862c-05614e003b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d07ec45c-5366-4897-9d6c-388e0d8741b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;normal_login_username&quot;)</value>
      <webElementGuid>c7e0eafd-b372-4f24-bc96-0602d48c4494</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='normal_login_username']</value>
      <webElementGuid>cec9e63f-224a-4b66-b0f5-03affacd6e2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='normal_login']/div/div/div/div/div/input</value>
      <webElementGuid>ba6f15bd-fdaf-4302-a91d-b22cb72c1d72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9f7a1d86-a3e2-4922-aabc-3cbd7039f9f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Email Address' and @id = 'normal_login_username' and @type = 'text']</value>
      <webElementGuid>54546c36-104d-4338-9add-3b1ff16b8365</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
