<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Log in_normal_login_password</name>
   <tag></tag>
   <elementGuidId>ad5c9aa9-46e9-4a79-b62f-7e7dc45c7b73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#normal_login_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='normal_login_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ecd307ed-0d00-4dd0-b2f5-e235947b50f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>60f1342d-0e0c-4d01-b74c-557a987b6463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>ebfeabb0-7b9d-45be-b06f-6cd37fb5654a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>normal_login_password</value>
      <webElementGuid>4ea537ae-67a7-45a8-a2c8-f2e01d81bae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>210feb73-85ee-4bb1-8011-317fc71c0af7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input css-w8mnev</value>
      <webElementGuid>abde8e40-6923-431c-bd22-d994941c8f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>A</value>
      <webElementGuid>563aba3e-33e3-4b0a-9b1a-25ad07b521fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;normal_login_password&quot;)</value>
      <webElementGuid>f01cd9ac-6f20-4c07-a711-78c0d81595f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='normal_login_password']</value>
      <webElementGuid>e17b4e24-d68f-4c62-812e-6d7b909eb535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='normal_login']/div[2]/div/div/div/div/span/input</value>
      <webElementGuid>d6516779-188d-464a-a660-ecb493009e01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>b55ccc94-6cf8-47ce-82b7-3cf8d55617a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Password' and @id = 'normal_login_password']</value>
      <webElementGuid>65aea1ca-7a6f-4c96-a87a-c460a6665cfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
